name: build
on:
    workflow_dispatch:
    merge_group:
    pull_request:
        types: [ opened, synchronize, edited ]
    workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: run hello world
        run: echo "hello world"

  call_wf:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      -   uses: actions/checkout@v4
      -   name: check current folder
          run: pwd && ls -la
      -   name: check workflows availables
          run: ls -la ./.github/workflows/
      -   name: Upload APK staging compat
          uses: ./.github/workflows/workflow2.yml@chore/workflows-test
